# Generated by Django 4.2.7 on 2024-09-02 16:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="SignificantEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("year", models.IntegerField()),
                ("impact", models.TextField()),
                ("source_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserSubmittedFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source_url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                            ("undetermined", "Undetermined"),
                        ],
                        default="under_review",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "notification_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("categories", models.ManyToManyField(to="nostalgia_app.category")),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_facts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("year", models.IntegerField()),
                ("is_outdated", models.BooleanField(default=False)),
                ("current_status", models.TextField(blank=True)),
                ("change_description", models.TextField(blank=True)),
                ("relevance_explanation", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 9, 2, 12, 33, 59, 644168)
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="items", to="nostalgia_app.category"
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("year", models.IntegerField()),
                ("relevance", models.TextField()),
                ("source_url", models.URLField()),
                ("isbn", models.CharField(blank=True, max_length=13)),
                ("cover_url", models.URLField(blank=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="books", to="nostalgia_app.category"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="APIFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("categories", models.ManyToManyField(to="nostalgia_app.category")),
            ],
            options={
                "unique_together": {("year", "title")},
            },
        ),
    ]
