# Generated by Django 4.2.7 on 2024-08-31 16:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nostalgia_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.RemoveField(
            model_name="informationitem",
            name="category",
        ),
        migrations.AddField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(
                related_name="books", to="nostalgia_app.category"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name="informationitem",
            name="categories",
            field=models.ManyToManyField(
                related_name="items", to="nostalgia_app.category"
            ),
        ),
        migrations.AddField(
            model_name="informationitem",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 31, 12, 9, 21, 330509)
            ),
        ),
        migrations.AddField(
            model_name="informationitem",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="informationitem",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="informationitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="significantevent",
            name="source_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="UserSubmittedFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("source_url", models.URLField()),
                ("is_approved", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("categories", models.ManyToManyField(to="nostalgia_app.category")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
