# Generated by Django 4.2.7 on 2024-09-02 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nostalgia_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationitem",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 9, 2, 12, 48, 38, 722261)
            ),
        ),
    ]
