# Generated by Django 4.2.7 on 2024-09-02 17:18

from django.db import migrations
from django.utils.text import slugify


def add_standard_categories(apps, schema_editor):
    Category = apps.get_model('nostalgia_app', 'Category')
    standard_categories = ['Music', 'News', 'Fashion', 'Sports', 'Technology', 'Politics', 'Entertainment', 'Science']
    for category_name in standard_categories:
        slug = slugify(category_name)  # Ensure slugs are created here
        Category.objects.get_or_create(name=category_name, defaults={'slug': slug})

class Migration(migrations.Migration):
    dependencies = [
        ("nostalgia_app", "0002_alter_informationitem_created_at"),
    ]

    operations = [migrations.RunPython(add_standard_categories),]
