# Generated by Django 4.2.7 on 2024-08-31 17:02

from django.db import migrations

def add_standard_categories(apps, schema_editor):
    Category = apps.get_model('nostalgia_app', 'Category')
    standard_categories = ['Music', 'News', 'Fashion', 'Sports', 'Technology', 'Politics', 'Entertainment', 'Science']
    for category_name in standard_categories:
        Category.objects.get_or_create(name=category_name)


class Migration(migrations.Migration):
    dependencies = [
        (
            "nostalgia_app",
            "0002_remove_book_category_remove_informationitem_category_and_more",
        ),
    ]

    operations = []
