# Generated by Django 4.2.7 on 2024-08-31 17:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nostalgia_app", "0003_add_standard_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubmittedfact",
            name="is_approved",
        ),
        migrations.AddField(
            model_name="usersubmittedfact",
            name="notification_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="usersubmittedfact",
            name="notification_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="usersubmittedfact",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="usersubmittedfact",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersubmittedfact",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_facts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersubmittedfact",
            name="status",
            field=models.CharField(
                choices=[
                    ("under_review", "Under Review"),
                    ("approved", "Approved"),
                    ("denied", "Denied"),
                    ("undetermined", "Undetermined"),
                ],
                default="under_review",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="informationitem",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 31, 13, 52, 6, 347483)
            ),
        ),
    ]
