# Generated by Django 4.2.7 on 2024-08-31 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nostalgia_app", "0004_remove_usersubmittedfact_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationitem",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 31, 14, 1, 13, 670982)
            ),
        ),
    ]
