# Generated by Django 4.2.7 on 2024-09-01 02:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("nostalgia_app", "0007_alter_informationitem_created_at_apifact"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubmittedfact",
            name="mention_profile",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usersubmittedfact",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_by_facts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="informationitem",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 31, 22, 50, 34, 720659)
            ),
        ),
    ]
