# Generated by Django 4.2.7 on 2024-09-01 02:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nostalgia_app", "0008_usersubmittedfact_mention_profile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubmittedfact",
            name="mention_profile",
        ),
        migrations.RemoveField(
            model_name="usersubmittedfact",
            name="submitted_by",
        ),
        migrations.AlterField(
            model_name="informationitem",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 31, 22, 59, 42, 291963)
            ),
        ),
    ]
