# Generated by Django 4.2.7 on 2024-09-01 03:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nostalgia_app", "0009_remove_usersubmittedfact_mention_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informationitem",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 31, 23, 3, 8, 911512)
            ),
        ),
    ]
